version: '3.7'
services:

  postgres:
    image: postgres:10
    command: postgres -c 'max_connections=10' -c 'superuser_reserved_connections=0' -c 'max_wal_senders=0'
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  postgres:
  mysql: